[tool.poetry]
name = "dynamodb-local"
version = "0.1.0"
description = ""
authors = ["icck <icck.n.n1111@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
boto3 = "^1.34.146"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
